using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Net.Sockets;

namespace IronStrife.MasterServer
{
    public static class Launcher
    {
        private static int lowestPortNumber = 1000;
        public static int GetNextPortNumber()
        {
            return lowestPortNumber++;
        }

        public static ServerInfo LaunchServer(int portNumber = -1, string fileName = "-1")
        {
            if (portNumber == -1) 
                portNumber = GetNextPortNumber();
            var gameName = "autoGeneratedServer";
            var description = "autoGeneratedServer";
            Console.WriteLine("Launching a new IronStrife server process");
            ProcessStartInfo startInfo = new ProcessStartInfo();
            if (fileName == "-1")
            {
                fileName = @"C:\Users\Eric\Desktop\TestBuild\test.exe";
            }
            startInfo.FileName = fileName;
            startInfo.Arguments = "-batchmode StartHeadlessServer " + gameName + " " + description + " " + portNumber;
            startInfo.Arguments = String.Format("-batchmode StartHeadlessServer {0} {1} {2}", portNumber, gameName, description);
            try
            {
                var process = Process.Start(startInfo);
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
            }
            lowestPortNumber = Math.Max(portNumber, lowestPortNumber);
            return new ServerInfo()
            {
                gameName = gameName,
                gameDescription = description,
                gametype = "autoGeneratedType",
                ipAddress = Globals.LocalAddress.ToString(),
                maxPlayers = 32,
                numConnectedPlayers = 0,
                port = portNumber
            };
        }
    }
}
